### ISSUE TITLE
Trying to upload a file gives Unknown type "upload.file"

### ISSUE THREAD

**Issue by umer936** [passchn/cakephp-assets#1]
From `http://localhost:8765/admin/assets/assets/add`

![image](https://user-images.githubusercontent.com/2078163/151016111-6935918f-cfed-413f-b0a9-92b8f7ba90cc.png)

Appears the same whether it is a .pdf, .jpg, or .pptx

Here's a `dd($this->request->getData())` added to the `add()` method

![image](https://user-images.githubusercontent.com/2078163/151016670-ab764451-27aa-4676-af37-0924e7fa183a.png)

**Comment by passchn** [comment]
I found the issue. I forgot to load the UploadPlugin in my Plugin: 
https://github.com/FriendsOfCake/cakephp-upload/issues/546 

I'll release a fixed version soon.

**Comment by passchn** [comment]
It should work now, I released version 0.1.3: 
https://github.com/passchn/cakephp-assets/releases/tag/v0.1.3 

That was the fix: 
https://github.com/passchn/cakephp-assets/commit/387c1f2499e718088e3f5a90a76600d3cf162402 

I just loaded the Plugin in my applications anyway, so I didn't notice the mistake. Sorry for that!

**Comment by umer936** [comment]
Awesome, thank you!

**Comment by passchn** [comment]
Thank you for using the plugin! I'm curious about any feedback you have :)
