### ISSUE TITLE
Update `josegonzalez/cakephp-upload` to V7

### ISSUE THREAD

**Issue by LordSimal** [passchn/cakephp-assets#10]
Currently the old v6 version causes notices with PHP 8.0+ because 
```
2023-03-31 20:40:19 notice: Optional parameter $data declared before required parameter $settings is implicitly treated as a required parameter
```
due to this change in the method param signature
https://github.com/FriendsOfCake/cakephp-upload/compare/6.0.0...7.0.0#diff-8e46612228f5130fd3e6d4b7e9d1140d3585c9ecf6a2eaaeb616108173ddb6aeL212

This can be reproduced if you try to regenerate the PHPStorm Metafile via `bin/cake phpstorm generate`
which gets provided by https://github.com/dereuromark/cakephp-ide-helper

Would be nice if this plugin gets updated to use v7 which fixes this problem.

**Comment by passchn** [comment]
I haven't worked on my planned v1 update in a while, I just noticed. Will make a quick v0.2 release instead soon :)

**Comment by passchn** [comment]
See https://github.com/brandcom/cakephp-assets/releases/tag/v0.2
